name: Markdown Embed Code From File
author:
  - "@tokusumi"
  - "@randy-jimenez"
description: Allows you to "import" code into your markdown files from elsewhere in your repository without having to manually copy and paste..
inputs:
  token:
    description: Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}.
    required: true
  markdown:
    description: Target path for your markdown file(s).
    required: false
    default: "README.md"
  message:
    description: Commit message for action.
    required: false
    default: "Embed code into Markdown."
runs:
  using: docker
  image: Dockerfile
branding:
  icon: bookmark
  color: green
