name: Embed code in README

on:
  push:
    branches:
      - "**"

jobs:
  embed-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
          ref: ${{ github.head_ref }}

      - name: Embed code into README.
        uses: "./"
        with:
          markdown: "README.md"
          message: "Embed code snippets into markdown."
          token: ${{ secrets.GITHUB_TOKEN }}
